package ryhma;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ryhma.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2017.07.23 19:19:35 // Generated by ComTest
 *
 */
public class JasenTest {



  // Generated by ComTest BEGIN
  /** testParse146 */
  @Test
  public void testParse146() {    // Jasen: 146
    Jasen aku = new Jasen(); 
    aku.parse("4 | Aku Ankka|    Kirkkokatu 1 | 64560 Ankkalinna | 050555555| aku@ankka.fi | "); 
    assertEquals("From: Jasen line: 149", 4, aku.getTunnusNro()); 
    assertEquals("From: Jasen line: 150", "Aku Ankka", aku.getNimi()); 
    assertEquals("From: Jasen line: 151", "4 | Aku Ankka | Kirkkokatu 1 | 64560 Ankkalinna | 050555555 | aku@ankka.fi", aku.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi206 */
  @Test
  public void testRekisteroi206() {    // Jasen: 206
    Jasen aku1 = new Jasen(); 
    assertEquals("From: Jasen line: 208", 0, aku1.getTunnusNro()); 
    aku1.rekisteroi(); 
    assertEquals("From: Jasen line: 210", 5, aku1.getTunnusNro()); 
    Jasen aku2 = new Jasen(); 
    aku2.rekisteroi(); 
    assertEquals("From: Jasen line: 216", 6, aku2.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi263 */
  @Test
  public void testGetNimi263() {    // Jasen: 263
    Jasen aku1 = new Jasen(); 
    aku1.taytaAkuAnkka(); 
    assertEquals("From: Jasen line: 266", "Aku Ankka", aku1.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKatuosoite277 */
  @Test
  public void testGetKatuosoite277() {    // Jasen: 277
    Jasen aku1 = new Jasen(); 
    aku1.taytaAkuAnkka(); 
    assertEquals("From: Jasen line: 280", "Paratiisitie 13", aku1.getKatuosoite()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPostiosoite291 */
  @Test
  public void testGetPostiosoite291() {    // Jasen: 291
    Jasen aku1 = new Jasen(); 
    aku1.taytaAkuAnkka(); 
    assertEquals("From: Jasen line: 294", "131313 Ankkalinna", aku1.getPostiosoite()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetPuhelin305 */
  @Test
  public void testGetPuhelin305() {    // Jasen: 305
    Jasen aku1 = new Jasen(); 
    aku1.taytaAkuAnkka(); 
    assertEquals("From: Jasen line: 308", "+33313131313", aku1.getPuhelin()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetSapo319 */
  @Test
  public void testGetSapo319() {    // Jasen: 319
    Jasen aku1 = new Jasen(); 
    aku1.aseta(5,"aku@ankka.fi"); 
    assertEquals("From: Jasen line: 322", "aku@ankka.fi", aku1.getSapo()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta416 */
  @Test
  public void testAseta416() {    // Jasen: 416
    Jasen jasen = new Jasen(); 
    assertEquals("From: Jasen line: 418", null, jasen.aseta(1, "Ankka Tupu")); 
    assertEquals("From: Jasen line: 419", "Tarkista puhelinnumero (Sallitut merkit 0-9, + ja välilyönti)", jasen.aseta(4, "kissa")); 
    assertEquals("From: Jasen line: 420", null, jasen.aseta(4, "040131313")); 
  } // Generated by ComTest END
}