package ryhma;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ryhma.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2017.07.23 19:28:58 // Generated by ComTest
 *
 */
public class TyokaluTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi105 */
  @Test
  public void testRekisteroi105() {    // Tyokalu: 105
    Tyokalu vasara = new Tyokalu(); 
    assertEquals("From: Tyokalu line: 107", 0, vasara.getTunnusNro()); 
    vasara.rekisteroi(); 
    assertEquals("From: Tyokalu line: 109", 3, vasara.getTunnusNro()); 
    Tyokalu ruuvari = new Tyokalu(); 
    ruuvari.rekisteroi(); 
    assertEquals("From: Tyokalu line: 112", 4, ruuvari.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse137 */
  @Test
  public void testParse137() {    // Tyokalu: 137
    Tyokalu ruuvari = new Tyokalu(); 
    ruuvari.parse("2  | 1  | 2  | pieni t‰htip‰‰ "); 
    assertEquals("From: Tyokalu line: 140", 2, ruuvari.getTunnusNro()); 
    assertEquals("From: Tyokalu line: 141", 2, ruuvari.getTyokaluNro()); 
    assertEquals("From: Tyokalu line: 142", "2 | 1 | 2 | pieni t‰htip‰‰", ruuvari.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta284 */
  @Test
  public void testAseta284() {    // Tyokalu: 284
    Tyokalu tyok = new Tyokalu(); 
    assertEquals("From: Tyokalu line: 286", null, tyok.aseta(3, "Rautaa")); 
    assertEquals("From: Tyokalu line: 287", "Rautaa", tyok.getLisatiedot()); 
  } // Generated by ComTest END
}