package ryhma;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ryhma.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2017.07.06 17:00:57 // Generated by ComTest
 *
 */
public class TyokalunNimiTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi71 */
  @Test
  public void testRekisteroi71() {    // TyokalunNimi: 71
    TyokalunNimi vasara = new TyokalunNimi(); 
    assertEquals("From: TyokalunNimi line: 73", 0, vasara.getTunnusNro()); 
    vasara.rekisteroi(); 
    assertEquals("From: TyokalunNimi line: 75", 1, vasara.getTunnusNro()); 
    vasara.vastaaVasara(); 
    assertEquals("From: TyokalunNimi line: 77", "vasara", vasara.getNimi()); 
    TyokalunNimi vasara2 = new TyokalunNimi("vasara"); 
    assertEquals("From: TyokalunNimi line: 79", "vasara", vasara2.getNimi()); 
    assertEquals("From: TyokalunNimi line: 80", 0, vasara2.getTunnusNro()); 
    vasara2.rekisteroi(); 
    assertEquals("From: TyokalunNimi line: 82", 2, vasara2.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse141 */
  @Test
  public void testParse141() {    // TyokalunNimi: 141
    TyokalunNimi vasara = new TyokalunNimi(); 
    vasara.parse("1     | vasara "); 
    assertEquals("From: TyokalunNimi line: 144", 1, vasara.getTunnusNro()); 
    assertEquals("From: TyokalunNimi line: 145", "1 | vasara", vasara.toString()); 
  } // Generated by ComTest END
}